### ISSUE TITLE
Send lowest deadline to pool

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#157] opened 2017-07-05 22:22 UTC
Can you add an enhancement to send the lowest deadline only? Maybe on each miner running or on the forwarding server, network miners submit deadlines to the forwarding server then it selects only the lowest and send to pool.

**Comment by Creepsky** [comment] 2017-07-06 08:03
What would be the benefit of that feature?
The chance to miss deadlines would increase proportionally to your TB, because first all of your drives needs to be read.

Think about the following scenario:

```
             your best deadline                      miner finishes reading your drives
             |                                       |
| -----------|---------------------- | --------------| 
|                                    |
block start                          best deadline in the network
```
You would lose it, even if you had actually won it, but your deadline was not send early enough.

The forwarding system would also be a problem: how can the master miner know, when all of the other miners are done reading?

It would take a lot of time to change the forwarding system to a real server system (right now it is just a normal HTTP server; serve and forget).

What is wrong with the current system? It is sending every deadline, that is
1. smaller then the target deadline
2. smaller then the last best found deadline

**Comment by N8Thrasher** [comment] 2017-07-08 10:12
It's just and idea, I've asked this because of the pools deadline penalty.

[https://www.burstnation.com/wbb/index.php?thread/1619-penalty-in-pool-s-question-for-clarity/&postID=24981#post24981](https://www.burstnation.com/wbb/index.php?thread/1619-penalty-in-pool-s-question-for-clarity/&postID=24981#post24981)

> "the penalty happens when you submit deadlines worse than the best one you sent to the pool.
> e.g. 2 miners different pc's same account. if both are mining at the same time at the same pool you will get a penalty causse the one will submit deadlines higher than the other. and vice versa"

**Comment by Creepsky** [comment] 2017-07-08 10:26
I understand your concerns and this feature can be helpful in some cases, for example reducing the traffic between miner and pool, but the creepMiner will not send deadlines that are worse than his own best found so far. So you dont have to be afraid to lose all your pending coins :)

If you have multiple miners that mine on the same pool, you can use the forwarding system to connect them. The master miner will also only send the best deadlines.

**Comment by N8Thrasher** [comment] 2017-07-08 11:04
I think its not working that way, even on its own.
take a look:
![f1](https://user-images.githubusercontent.com/24593637/27984734-e199e846-63e5-11e7-8e79-214b709f74c2.PNG)

@13:57:42 it found a deadline for 4m 22d 08:13:42 at the same time it found another 2m 22d 08:54:09 and @13:57:44 it found a much lower deadline 2m 0d 06:17:24 but it still send all those deadlines to the pool.

**Comment by Creepsky** [comment] 2017-07-08 11:38
So it is like this:

1. **4m** 22d 08:13:42 found + submitted
2. **2m 22d** 08:54:09 found + submitted
3. **2m 0d** 06:17:24 found + submitted

Nothing wrong here.
The penalty rule says: "you will get a penalty for every deadline you send, that is higher than the last best one you send". So by definition we should not get a penalty :) 

1 > 2 > 3

But because the pool is too slow to handle all requests at once, the confirmation looks like this:
1. **2** got confirmed by server
2. **3** got confirmed by server
3. **1** got confirmed by server

Try it on another pool that is not that much populated and you will see the confirmation order will be
1 -> 2 -> 3.

Now we can debate a long time if its the pools or the miners fault :D or I simply ask you: do you need this feature very urgent?
If not, I will put this on the backlog, because it is really a lot of work).

**Comment by N8Thrasher** [comment] 2017-07-08 11:54
lol! No its not urgent, like I said its just an idea if it can be done.

thanks for your time :)

**Comment by svenerxleben** [comment] 2018-02-12 23:18
Could it be possible to add a feature for sending any deadline which fits the pools deadline? I get a lot of deadlines like this:
nonce submitted (00:00:01)
which results in 
error on submitting nonce! (00:00:01)
But it doesn't look for any other deadlines anymore.

**Comment by modislaszlo** [comment] 2018-02-13 21:05
It think this would be great addition for small miners. I have read time of 18 seconds so for me this option would be perfect.

**Comment by nitr8** [comment] 2018-03-13 13:26
updated labels and closing - obsolete

**Closed by nitr8** 2018-03-13 13:26 UTC
Labels: obsolete, wontfix
