### ISSUE TITLE
GPU Mining loads CPU

### ISSUE THREAD

**Issue by utmuk** [Creepsky/creepMiner#305] opened 2018-02-10 20:03 UTC
I tried GPU mining with 1070 card, but it loads CPU to 100% and thus scan times are low. Is this normal?

**Comment by utmuk** [comment] 2018-02-10 20:41
As a result there is no difference with BlagoMiner despite the fact that CPU is a very slow one and GPU is quite fast

**Comment by utmuk** [comment] 2018-02-10 20:43
Using Windows, drivers installed OK, GPU plotting works fine

**Comment by Creepsky** [comment] 2018-02-10 21:57
I dont know, maybe?

**Comment by utmuk** [comment] 2018-02-11 05:20
What do you mean?)))

**Comment by Creepsky** [comment] 2018-02-11 08:30
Please read https://github.com/Creepsky/creepMiner/blob/master/ISSUE_TEMPLATE.md (thats by the way the long text you removed when you created your issue). I can only guess what the problem is, if you give me these high quality informations. Imagine you go to a restaurant and when you are asked for your order you just reply "me food, me hungry", sitting there in your pyjama ;)

**Comment by utmuk** [comment] 2018-02-11 09:25
I am sorry for that, I will try to ask the question by those guidelines.
I have a computer with 17 plotted 8TB drives, a slow AMD processor (Athlon X4 840), Nvidia Graphics Card model 1070, 8GB RAM, Windows 10 64bit installed.
I am trying to use GPU-assisted mining. The Creepminer 1.7.16 doesn't have support for "/setup" or "-setup" switches, so I am editing config file by hand. I will post it in the next message. The only thing I change in it is that I try "CUDA" and "OPENCL" in the line:
        "processorType" : "OPENCL",
The rest of the config is always the same.
I try CUDA and OPENCL with version 1.7.16 and get error like this:
![1](https://user-images.githubusercontent.com/28525658/36071802-8410d5f4-0f25-11e8-8cc6-9b46f19a327a.PNG)
![2](https://user-images.githubusercontent.com/28525658/36071803-842df530-0f25-11e8-8f53-eede8fd640c2.PNG)
[creepMiner_20180211_060403.400082.log](https://github.com/Creepsky/creepMiner/files/1714221/creepMiner_20180211_060403.400082.log)
That's why I think the latest version doesn't support GPU assisted mining. So I try version 1.7.8. It starts, but I get very slow reads and high CPU load. Here are the screenshots and log:
[creepMiner_20180211_060743.115733.log](https://github.com/Creepsky/creepMiner/files/1714223/creepMiner_20180211_060743.115733.log)
![4](https://user-images.githubusercontent.com/28525658/36071818-dde53f52-0f25-11e8-8a36-69c58b6a56b2.PNG)
![5](https://user-images.githubusercontent.com/28525658/36071819-de03b018-0f25-11e8-93c0-4282f06e1850.PNG)

**Comment by utmuk** [comment] 2018-02-11 09:26
{
    "logging" : {
        "config" : "information",
        "general" : "information",
        "logfile" : true,
        "miner" : "information",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : true,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceFoundTooHigh" : false,
            "nonceSent" : true,
            "plotDone" : false
        },
        "outputType" : "terminal",
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "progressBar" : {
            "fancy" : false,
            "steady" : true
        },
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "useColors" : true,
        "wallet" : "fatal"
    },
    "mining" : {
        "benchmark" : {
            "active" : false,
            "interval" : 60
        },
        "bufferChunkCount" : 8,
        "cpuInstructionSet" : "AVX",
        "getMiningInfoInterval" : 3,
        "gpuDevice" : 0,
        "gpuPlatform" : 0,
        "intensity" : 3,
        "maxBufferSizeMB" : 2500,
        "maxPlotReaders" : 0,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 1000,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "D:/p",
            "E:/p",
            "F:/p",
            "G:/p",
            "H:/p",
            "I:/p",
            "J:/p",
            "K:/p",
            "L:/p",
            "M:/p",
            "N:/p",
            "O:/p",
            "P:/p",
            "Q:/p",
            "R:/p",
            "S:/p",
            "T:/p"
        ],
        "processorType" : "OPENCL",
        "rescanEveryBlock" : false,
        "submissionMaxRetry" : 3,
        "targetDeadline" : "1y 0m 0d 00:00:00",
        "timeout" : 30,
        "urls" : {
            "miningInfo" : "http://0-100-pool.burst.cryptoguru.org:8124",
            "submission" : "http://0-100-pool.burst.cryptoguru.org:8124",
            "wallet" : "http://0-100-pool.burst.cryptoguru.org:8124"
        },
        "useInsecurePlotfiles" : true,
        "wakeUpTime" : 58,
        "walletRequestRetryWaitTime" : 10,
        "walletRequestTries" : 5
    },
    "webserver" : {
        "activeConnections" : 4,
        "calculateEveryDeadline" : false,
        "connectionQueue" : 30,
        "credentials" : {
            "pass" : "",
            "user" : ""
        },
        "cumulatePlotsizes" : true,
        "forwardMinerNames" : true,
        "forwardUrls" : [

        ],
        "start" : true,
        "url" : "http://192.168.1.3:8080"
    }
}

**Comment by Creepsky** [comment] 2018-02-11 09:35
Thank you, thats a lot better :) ❤️  
So you are using 1.7.16 but it is build without GPU support (for more informations you can read this: https://github.com/Creepsky/creepMiner/wiki/FAQ#why-are-there-different-executables).

1.7.16 is an automatical build - TODO: I will change the script so it will also produce a GPU version for both, Linux and Windows (if possible).

**Comment by utmuk** [comment] 2018-02-11 09:38
Thank you. But what about the CPU load problem? Won't it still be there?

**Comment by Creepsky** [comment] 2018-02-11 09:52
You have a lot of drives connected, and you have `"maxPlotReaders" : 0,`, so it means your CPU will use 17 threads to read all drives simultaneously. You can lower your maxPlotReaders (set it to a fixed value) to limit your CPU load.

Unfortunately it is not possible to completely remove the CPU load, because the GPU can't run the C++ miner code (open files, read them, ...).
Maybe I will find a more optimized algorithm some day.

**Comment by nitr8** [comment] 2018-04-10 14:57
Closing, as this has gone off topic - if you still have an open issue please open a new issue

**Closed by nitr8** 2018-04-10 14:57 UTC
Labels: change
